#!/usr/bin/env bash
# tick tock
hour=0
minute=1
echo "Hour: $hour"
while [ $hour -lt 13 ]
do
	echo "$minute"
	if [ $minute -eq 59 ]; then
		hour=$((hour + 1))
		if [ $hour -ne 13 ]; then 
			echo "Hour: $hour"
		fi
		minute=1
	fi
	minute=$((minute + 1))
done
