#!/usr/bin/env bash
# coding in bash: to cry or not to cry

if [ ! -e school ]
then
	echo "school file does not exist"
else
	echo "school file exists"
	if [ ! -s school ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f school ]
	then
		echo "school is a regular file"
	fi
fi
