#!/usr/bin/env bash
# abcdefg

sudo touch /var/run/myscript.pid
echo $$ | sudo tee -a /var/run/myscript.pid 

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!' SIGINT

trap 'sudo rm -f /var/run/myscript.pid && exit' SIGQUI

while true
do
	echo "To infinity and beyond"
done

