#!/usr/bin/env bash
# abcdefg

function start_my_process() {
	./manage_my_process
        pgrep './manage_my_process' > sudo tee -a /var/run/my_process.pid
}

function stop_my_process() {
	pkill -9 './manage_my_process'
        sudo rm -f /var/run/my_process.pid
}

if [[ $1 == "start" ]]
then
	start_my_process
elif [[ $1 == "stop" ]]
then
	stop_my_process
	echo "manage_my_process stopped"
elif [[ $1 == "restart" ]]
then
	stop_my_process
	start_my_process
	echo "manage_my_process restarted"
else
	echo 'Usage: manage_my_process {start|stop|restart}'
fi

unset -f start_my_process
unset -f stop_my_process
